set -g default-terminal 'xterm-256color'
set -g default-shell /bin/zsh
set -g base-index 1
set -g renumber-windows on
set -ga terminal-overrides ',alacritty:RGB:smcup@:rmcup@'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g status-style 'bg=#333333 fg=#5eacd3'
set -g status-left-length 80
set -g status-left '#(tmux-session-status)'
set -s escape-time 0
set -g automatic-rename off
set -g allow-rename on
set-hook -g after-new-window 'run-shell "tmux-window-name"'
set -g mouse on
set -g status-interval 1

bind r source-file ~/.tmux.conf
bind -n MouseDown1StatusLeft choose-tree -Zs

bind -r n new-window
bind % split-window -h
bind '"' split-window -v

# vim-like navigation
bind -r h previous-window
bind -r l next-window
bind -r j switch-client -p
bind -r k switch-client -n

unbind x
unbind w
unbind f
unbind t
bind-key x run-shell 'tmux-kill-default-windows'
bind-key f display-popup -E "tmux-sessionizer"
bind-key w display-popup -E "tmux-sessionizer"
bind-key C-f display-popup -E "tmux-sessionizer"
bind-key C-w display-popup -E "tmux-sessionizer"
bind-key t display-popup -E "tmux-sessionizer ~/tmp"
bind-key H display-popup -E "tmux-sessionizer ~/"

# pane management
bind-key J display-popup -E "tmux-join-pane -v"
bind-key V display-popup -E "tmux-join-pane -h"
bind-key B break-pane -d
bind-key S swap-pane -U
bind-key D swap-pane -D

# network tools
bind-key m command-prompt -p "mtr:" "display-popup -E -w 80% -h 80% 'tmux-popup-persist mtr %%'"
bind-key p command-prompt -p "ping:" "display-popup -E -w 80% -h 80% 'tmux-popup-persist ping %%'"
